services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ~j5jlBd|B%-V
      POSTGRES_DB: ihaveplan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./app/.env:/app/.env
    depends_on:
      - postgres
    networks:
      - backend_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  pgdata:

networks:
  backend_network:
    driver: bridge